### PR TITLE
fix(DSL): improve keyword mapping handling for nested fields

### LINKED ISSUE #42: Nested / Dot notation whereExact Fails
## Describe the bug
When using `whereExact` with either a `queryNested` or by using dot notation a `ParameterException` occurs. This seems to be a direct result of the `parseRequiredKeywordMapping` helper in the Bridge.

## To Reproduce
Create a nested field mapping as part of the schema make sure it has a keyword mapping and then query in either of these fashions:

```php
       ConfiguredItem::queryNested('request', function ($query) use ($item) {
            $query->whereExact('item_number', $item['item_number']);
        })->toSql();
```

```php
       ConfiguredItem::whereExact('request.business_unit', $item['business_unit']))->toSql();
```

## Expected behavior
This should work as long as long as the field is mapped to a keyword field.

---
**Screenshots**:

image

image

### PR DESCRIPTION
**Pull request by use-the-fork**
This fixes the mapping issue bug when using whereExact for a field requiring a keyword lookup deeper than 1 level.

The methodology now traverses the returned array instead of only looking one level down. In addition to that I leverage the getFieldMapping function instead of getting ALL the mappings. This makes it easier to traverse the array.

Fixes #42

### CODE REVIEW

**Comment by use-the-fork** [comment]
@pdphilip This is ready for you to look at. Not a huge change but the issue is resolved and I added tests to cover all mapping scenarios.

**Comment by pdphilip** [comment]
Thanks, @use-the-fork - will review the first chance I get; looks good, though.

**Comment by pdphilip** [comment]
@use-the-fork - this one is good to go. I've refactored the bridge for `fieldMapping()` to get a key/value array of fields and types. Useful feature so brought this into the Schema and Query builder as well. 

The test is passing, but feel free to have a look at your end as well. Nice one.

**Comment by use-the-fork** [comment]
@pdphilip your changes look good to me. I think your good to merge. Only thing I may add an issue for to look at later is the fact that we should.prob give the option to perform unsafe queries on where exact. 

Reason being if you do 3 whereExacts in a call you technically query elastic 4 times. It would be nice to allow the option to skip the check if a dev is confident in there feild mapping. 

Other option may be to combine and do a single call and cache it? I'm not sure just not crazy about the overhead.

**Comment by pdphilip** [comment]
Good point & not too hard to do. We can cache the first need for a map lookup in the bridge itself. Then reference it on subsequent lookups.

Will just need to know all the possible fields upfront, and make sure the lookup applies to the current field only.

I'll work on this tomorrow

**Comment by use-the-fork** [comment]
> Good point & not too hard to do. We can cache the first need for a map lookup in the bridge itself. Then reference it on subsequent lookups.
> 
> Will just need to know all the possible fields upfront, and make sure the lookup applies to the current field only.
> 
> I'll work on this tomorrow

If you go this route it may be better to do the full map lookup like you did before. Then use Arr::dot to flatten the whole thing and look for keyword feilds that way. Should be much easier to traverse.

**Pull request merged**
