### PR TITLE
Added the ability to sort for non-existent fields and fixed connection error

### PR DESCRIPTION
**Pull request by ildar-developer**

### CODE REVIEW

**Comment by pdphilip** [comment]
Thanks @ildar-developer 

PRs are welcome and encouraged. Basic etiquette though is to at least describe your contribution (beyond the title) to provide context for us maintainers.

Please do so by:
- Stating the issue you encountered / or the feature you needed. 
- If there was an issue, provide examples so that we can try to recreate it ourselves.
- Reference ES documentation (unless completely not needed)
- Describe the changes you made.

Thanks!

**Comment by ildar-developer** [comment]
I'm sorting by merchandising, and not all products have the merchandising property; if you don't specify unmapped_type, elastic will complain. I added the ability to add unmapped_type

**Comment by ildar-developer** [comment]
the second point is related to the fact that we cannot use 2 models since connect is 1 for two, so I specified clone for getConnection

**Comment by pdphilip** [comment]
As per my last message:

> * If there was an issue, provide examples so that we can try to recreate it ourselves.

**Comment by ildar-developer** [comment]
Data structure:
`{
                            "id": 1544837,
                            "offer_id": 1363809,
                            "price": "11000.00",
                            "price_not_discount": "22000.00",
                            "available_quantity": 1,
                            "discount_percent": 50,
                            "store": {
                                "id": 31,
                                "name": "Rich Classic Women"
                            }
                        },
                        {
                            "id": 2954243,
                            "offer_id": 1363809,
                            "price": "11000.00",
                            "price_not_discount": "22000.00",
                            "available_quantity": 0,
                            "discount_percent": 50,
                            "store": {
                                "id": 3,
                                "name": "IM VipAvenue"
                            }
                        },`

Снимок экрана 2024-08-29 в 19 09 32

There will be an error because merchandising.sale does not exist

Снимок экрана 2024-08-29 в 19 13 32

**Comment by ildar-developer** [comment]
Second error, try making a request in 2 modules
Снимок экрана 2024-08-29 в 19 15 49

$query->get() will return selection and not Carryover, below is a screenshot of how to fix it

**Comment by ildar-developer** [comment]
https://www.elastic.co/guide/en/elasticsearch/reference/current/sort-search-results.html#_ignoring_unmapped_fields

**Comment by pdphilip** [comment]
Ok the issue where starting a new query when another is in progress checks out - I'll need to run a few more tests to make sure that there are no unintended side effects with the rest of the package.

For unmapped, that's fine. 

There's a PR before this one that's being worked on that brings a significant refactor to the package. I'll need to ship that one first before I can do this one. I'll let you know

**Comment by ildar-developer** [comment]
thanks for the feedback

**Comment by pdphilip** [comment]
> will you add unmapped too?

yes

**Comment by pdphilip** [comment]
@ildar-developer - an earlier PR has been merged which is a reflector of the package, so your PR is way out of sync. I'll bring in your two changes manually and tag you as a contributor on the next release.

**Pull request closed without merging**
